version: 1.0.{build}
image: Visual Studio 2019
branches:
  only:
    - master
environment:
    my_encrypted_sonarqube_token:
        secure: auSP7uJIC8Y5I0AW97f0ANIOLXxkszux38+nFJhry4PFvH1MBd1xfBFMcA30a8Z9  
install:
    - choco install "sonarscanner-msbuild-netcoreapp2.0" -y
before_build:
    - cmd: nuget restore "Angular .NET Core RESTfulAPI1.sln"
    # AppVeyor does not decrypt the secure env vars for PR builds (prevents someone from submitting PR with malicious build script displaying those variables)
    #- dotnet sonarscanner begin /key:"HelloWorldTypescriptWebpack" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=%my_encrypted_sonarqube_token%" /o:"gregtrevellick-github"
    #- ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet sonarscanner begin /key:"HelloWorldTypescriptWebpack" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=$env:my_encrypted_sonarqube_token" /o:"gregtrevellick-github" /v:"$env:APPVEYOR_BUILD_NUMBER" }'
    - dotnet tool install -g dotnet-sonarscanner
    - dotnet sonarscanner begin /key:"AzureDevOpsBlazorRadiator" /d:"sonar.host.url=https://sonarcloud.io" /d:"sonar.login=%my_encrypted_sonarqube_token%" /o:"gregtrevellick-github"
build:
    project: "Angular .NET Core RESTfulAPI1.sln"
    verbosity: minimal
after_build:
    # AppVeyor does not decrypt the secure env vars for PR builds (prevents someone from submitting PR with malicious build script displaying those variables)
    #- dotnet sonarscanner end /d:"sonar.login=%my_encrypted_sonarqube_token%"
    #- ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & dotnet sonarscanner end /d:"sonar.login=$env:my_encrypted_sonarqube_token" }'
    - dotnet sonarscanner end /d:"sonar.login=%my_encrypted_sonarqube_token%"
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true