version: 1.0.{build}
image: Visual Studio 2017
branches:
  only:
    - master
environment:
    my_encrypted_sonarqube_token:
        secure: 94Py9ytqrmqFVtmUiyayJJ4Hgg2vjF1+YuRJldGGWO82/9zEens+sCjeh7wzc2Le
install:
    - choco install "sonarscanner-msbuild-net46" -y
before_build:
    - cmd: nuget restore "Angular .NET Core RESTfulAPI1.sln"
    - choco install opencover.portable
    - choco install codecov
    # AppVeyor does not decrypt the secure env vars for PR builds (prevents someone from submitting PR with malicious build script displaying those variables)
    #- SonarScanner.MSBuild.exe begin /k:"HelloWorldTypescriptWebpack" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=%my_encrypted_sonarqube_token%" /d:"sonar.organization=gregtrevellick-github"
    - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & SonarScanner.MSBuild.exe begin /k:"HelloWorldTypescriptWebpack" /d:"sonar.host.url=https://sonarqube.com" /d:"sonar.login=$env:my_encrypted_sonarqube_token" /d:"sonar.organization=gregtrevellick-github" /v:"$env:APPVEYOR_BUILD_NUMBER" }'
build:
    project: "Angular .NET Core RESTfulAPI1.sln"
    verbosity: minimal
after_build:
    # AppVeyor does not decrypt the secure env vars for PR builds (prevents someone from submitting PR with malicious build script displaying those variables)
    #- SonarScanner.MSBuild.exe end /d:"sonar.login=%my_encrypted_sonarqube_token%"
    - ps: 'if (-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) { & SonarScanner.MSBuild.exe end /d:"sonar.login=$env:my_encrypted_sonarqube_token" }'
notifications:
- provider: Email
  to:
  - gtrevellick@googlemail.com
  on_build_success: false
  on_build_failure: false
  on_build_status_changed: true
